deployment:
  image:
    repository: ghcr.io/dramatikman/mlhl-gradwork-web-ui
    tag: latest

  ingress:
    hosts:
      - host: gw.sergeypavlov.dev
        paths:
          - path: /
            pathType: Prefix
    tls:
    - secretName: tls.sergeypavlov.dev
      hosts:
        - gw.sergeypavlov.dev
