name: deploy

on:
  workflow_dispatch:

jobs:

  deploy:

    name: Deploy to remote via SSH
    runs-on: ubuntu-latest

    steps:

      - name: Executing remote SSH commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            rm -rf ${{ github.event.repository.name }} || echo "Nothing to remove."
            git clone git@github.com:${{ github.repository }}.git ${{ github.event.repository.name }}
            && helm dependency update ${{ github.event.repository.name }}/chart
            && helm upgrade
              --install
              --atomic
              --set 'deployment.image.tag=${{ github.sha }}'
              gwui ${{ github.event.repository.name }}/chart
            && rm -rf ${{ github.event.repository.name }}
